version: "3.9"

services:
  message-broker:
    image: rabbitmq:3.11
    container_name: message-broker
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    networks:
      - dev-network
  log-service:
    container_name: log-service
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - dev-network
    ports:
      - 80:8081
    environment:
      AMQP_CONN_URI: amqp://guest:guest@message-broker:5672/
      ENV: dev
      MONGODB_CONN_URI: mongodb+srv://IkehAkinyemi:kwZN74bwGnvsO4xJ@cluster0.wqrmh26.mongodb.net/audit-log?retryWrites=true&w=majority
      HTTP_PORT: 8081
    depends_on:
      - message-broker

networks:
  dev-network:
    driver: bridge