env: dev # environment 
mongodb: 
  connURI: "mongodb+srv://IkehAkinyemi:kwZN74bwGnvsO4xJ@cluster0.wqrmh26.mongodb.net/audit-log?retryWrites=true&w=majority" # connection string for MongoDB
port: 8081
amqp:
  connURI: "amqp://guest:guest@localhost:5672/" # connection string for rabbitMQ

